<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(SolutionDir)CommonPackageHandling.targets" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lz.Core</RootNamespace>
    <PackageId>Lz.Core</PackageId>
    <Description>Lz core interfaces, config models, and orchestration</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pulumi" Version="3.*" />
    <PackageReference Include="Pulumi.Automation" Version="3.*" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="YamlDotNet" Version="16.*" />
  </ItemGroup>

</Project>
