// Generated by LazyMagic from Startup.t.cs - modify Startup.t.cs and then regenerate to update.
// Create a separate Startup.cs file for project specific startup code.

public partial class Startup
{
    partial void ConfigureSvcs(IServiceCollection services);
}
