// Generated by LazyMagic from Program.t.cs - modify Program.t.cs and then regenerate to update.

using Serilog;

// Configure Serilog to write to console and file for local debugging
// Log to LocalWebService project folder
var logPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../LocalWebService.log"));
if (File.Exists(logPath)) File.Delete(logPath);
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .MinimumLevel.Override("Microsoft", Serilog.Events.LogEventLevel.Warning)
    .MinimumLevel.Override("System", Serilog.Events.LogEventLevel.Warning)
    .WriteTo.Console()
    .WriteTo.File(logPath,
        outputTemplate: "{Timestamp:HH:mm:ss.fff} [{Level:u3}] {SourceContext} {Message:lj}{NewLine}{Exception}")
    .CreateLogger();

Console.WriteLine($"[LocalWebService] Logging to file: {logPath}");

var builder = WebApplication.CreateBuilder(args);

// Use Serilog for logging
builder.Host.UseSerilog();

// Add systemconfig.yaml to IConfiguration (loads all YAML keys including Integrations, Profile, Tenants, etc.)
// Resolves environment-aware config: systemconfig.yaml (plain) or systemconfig.{env}.yaml
// Environment is detected from env.yaml or folder name convention (_Dev*, _Test*, _Prod*)
var systemConfigPath = UtilModule.SystemConfigResolver.ResolveFromDirectory(
    Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "../..")));
if (systemConfigPath is not null)
{
    builder.Configuration.AddYamlFile(systemConfigPath, optional: true, reloadOnChange: false);
    Console.WriteLine($"Loaded configuration from {systemConfigPath}");
}
else
{
    Console.WriteLine("Warning: No systemconfig.yaml or systemconfig.{env}.yaml found");
}

// Add services to the container
builder.Services.AddControllers()
    .AddNewtonsoftJson();

builder.Services.AddHttpContextAccessor();
builder.Services.AddHttpClient();

// Configure multi-scheme authentication from configuration
builder.Services.AddMultiSchemeAuthentication(builder.Configuration);

// Add CORS
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.SetIsOriginAllowed(origin =>
                  origin.StartsWith("https://") || origin.StartsWith("http://"))
              .WithHeaders(
                  "Authorization",
                  "lz-auth-id",
                  "lz-authname")
              .AllowAnyHeader()
              .WithMethods(
                  "GET",
                  "HEAD",
                  "PUT",
                  "OPTIONS",
                  "PATCH",
                  "POST",
                  "DELETE")
              .WithExposedHeaders(
                  "Date",
                  "x-api-id",
                  "lz-auth-id",
                  "lz-authname")
              .SetPreflightMaxAge(TimeSpan.FromSeconds(600))
              .DisallowCredentials();
    });
});

// Add health checks
builder.Services.AddHealthChecks();

// Add request logging (configured from systemconfig.yaml)
builder.Services.AddRequestLogging(builder.Configuration);

// Add request rewriter (configured from appsettings.json or defaults)
builder.Services.AddRequestRewriter(builder.Configuration);

// Configure services (will be generated)
var startup = new Startup(builder.Configuration);
startup.ConfigureServices(builder.Services);

var app = builder.Build();

// Configure the HTTP request pipeline
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

// Request logging (early in pipeline to capture all requests)
app.UseRequestLogging();

// Apply request path rewrites (BEFORE routing so routes match rewritten paths)
app.UseRequestRewriter();

app.UseRouting();

app.UseCors();

// Multi-scheme authentication middleware
app.UseMultiSchemeAuthenticationMiddleware();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapHealthChecks("/health");

// Hook for host-specific endpoint mapping (e.g., SignalR hubs)
startup.ConfigureEndpoints(app);

app.Run();
