// Generated by LazyMagic from Startup.t.cs - modify Startup.t.cs and then regenerate to update.
// Create a separate Startup.cs file for project specific startup code.

public partial class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public static IConfiguration Configuration { get; private set; }

    // This method gets called to configure services. ConfigureSvcs will be generated.
    public void ConfigureServices(IServiceCollection services)
    {
        // Configure integration endpoints
        // Uses tunnel ports from systemconfig.yaml for local dev
        services.AddIntegrations(Configuration);

        // Register AWS Secrets Manager service
        // Uses AWS Profile from systemconfig.yaml for credentials
        var profile = Configuration["Profile"];
        var region = Configuration["Region"] ?? "us-east-1";
        var secretPrefix = Configuration.GetSection("SecretsManager")["SecretPrefix"] ?? "";

        services.AddAwsSecretsManager(Configuration, options =>
        {
            options.Region = region;
            options.SecretPrefix = secretPrefix;
            options.UseConfiguredProfile = true;
        });
        Console.WriteLine($"AWS Secrets Manager configured for region: {region}, profile: {profile ?? "(default)"}");

        // Hook for host-specific service registrations (before modules are registered)
        // Implement this partial method in a separate Startup.cs to register
        // implementation-specific services (e.g., Users.Keycloak, Store.SmartStore)
        ConfigureHostServices(services);

        ConfigureSvcs(services);
        services.AddControllers(options =>
        {
            // Add the AuthorizationExceptionFilter to convert AuthorizationException
            // to appropriate HTTP status codes (401, 403, 400, 503)
            options.AddAuthorizationExceptionFilter();
            // Add the FlowThroughExceptionFilter to convert FlowThroughException
            // to appropriate HTTP status codes (502 Bad Gateway, etc.)
            options.AddFlowThroughExceptionFilter();
        }).AddNewtonsoftJson();
    }

    /// <summary>
    /// Override in host's Startup.cs to register implementation-specific services.
    /// Called before modules are registered, allowing modules to depend on interfaces
    /// that are implemented by services registered here.
    /// </summary>
    partial void ConfigureHostServices(IServiceCollection services);

    /// <summary>
    /// Override in host's Startup.cs to map additional endpoints (e.g., SignalR hubs).
    /// Called after app.MapControllers() in the request pipeline.
    /// </summary>
    public void ConfigureEndpoints(WebApplication app)
    {
        ConfigureHostEndpoints(app);
    }

    /// <summary>
    /// Implement in host's Startup.cs to add endpoint mappings.
    /// </summary>
    partial void ConfigureHostEndpoints(WebApplication app);
}
