//----------------------
// <auto-generated>
//     Generated by LazyMagic. Do not edit directly. Changes will be overwritten.
//     Contains flow-through helper methods for {projectName}ControllerBase.
// </auto-generated>
//----------------------
namespace {projectName}
{
    /// <summary>
    /// Partial class containing flow-through helper methods.
    /// These are separated from the main controller base to avoid NSwag processing issues.
    /// </summary>
    public partial class {projectName}ControllerBase
    {
        /// <summary>
        /// The module path prefix that will be stripped from paths when forwarding requests.
        /// </summary>
        private const string ModulePathPrefix = "/{modulePath}/";

        // ============ Path and Query Helpers ============

        /// <summary>
        /// Strips the module path prefix from a path for forwarding to external service.
        /// E.g., "/{projectName}/api/orders/123" becomes "/api/orders/123"
        /// </summary>
        protected virtual string StripModulePrefix(string path)
        {
            if (path.StartsWith(ModulePathPrefix, StringComparison.OrdinalIgnoreCase))
            {
                return path.Substring(ModulePathPrefix.Length - 1); // Keep the leading slash
            }
            // Also handle case without trailing slash in prefix
            var prefixWithoutSlash = ModulePathPrefix.TrimEnd('/');
            if (path.StartsWith(prefixWithoutSlash, StringComparison.OrdinalIgnoreCase))
            {
                return path.Substring(prefixWithoutSlash.Length);
            }
            return path;
        }

        /// <summary>
        /// Builds a query string from a dictionary of query parameters.
        /// Null values are excluded from the query string.
        /// Handles IEnumerable values by repeating the parameter for each value.
        /// Boolean values are serialized as lowercase "true"/"false" for OData compatibility.
        /// </summary>
        protected virtual string BuildQueryString(IDictionary<string, object> queryParams)
        {
            if (queryParams == null || queryParams.Count == 0)
                return string.Empty;

            var queryParts = new List<string>();

            foreach (var kvp in queryParams)
            {
                var value = kvp.Value;
                if (value == null)
                    continue;

                var encodedName = Uri.EscapeDataString(kvp.Key);

                // Handle different value types
                if (value is bool boolValue)
                {
                    // OData requires lowercase "true"/"false"
                    queryParts.Add($"{encodedName}={boolValue.ToString().ToLowerInvariant()}");
                }
                else if (value is string strValue)
                {
                    queryParts.Add($"{encodedName}={Uri.EscapeDataString(strValue)}");
                }
                else if (value is System.Collections.IEnumerable enumerable && !(value is string))
                {
                    // Handle IEnumerable values (like orderby, select, expand) by repeating the parameter
                    foreach (var item in enumerable)
                    {
                        if (item != null)
                        {
                            var itemStr = item is bool b ? b.ToString().ToLowerInvariant() : item.ToString();
                            queryParts.Add($"{encodedName}={Uri.EscapeDataString(itemStr)}");
                        }
                    }
                }
                else
                {
                    queryParts.Add($"{encodedName}={Uri.EscapeDataString(value.ToString())}");
                }
            }

            return queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : string.Empty;
        }

        /// <summary>
        /// Substitutes OData parameter aliases (@paramName) in the path with values from queryParams.
        /// After substitution, removes the used parameters from queryParams to avoid duplicate query string params.
        /// </summary>
        protected virtual string SubstitutePathAliases(string path, IDictionary<string, object> queryParams)
        {
            if (queryParams == null || queryParams.Count == 0)
                return path;

            // Regex to find @paramName patterns (alphanumeric and underscore after @)
            var aliasPattern = new System.Text.RegularExpressions.Regex(@"@(\w+)");
            var keysToRemove = new List<string>();

            var substitutedPath = aliasPattern.Replace(path, match =>
            {
                var paramName = match.Groups[1].Value; // Get the name without @

                if (queryParams.TryGetValue(paramName, out var value) && value != null)
                {
                    keysToRemove.Add(paramName);

                    // Format the value appropriately for URL path
                    if (value is bool boolValue)
                        return boolValue.ToString().ToLowerInvariant();
                    if (value is string strValue)
                        return Uri.EscapeDataString(strValue);
                    return Uri.EscapeDataString(value.ToString());
                }

                // If no matching param found, leave the alias as-is
                return match.Value;
            });

            // Remove substituted params from queryParams so they aren't also added as query string
            foreach (var key in keysToRemove)
            {
                queryParams.Remove(key);
            }

            return substitutedPath;
        }

        // ============ Request Building ============

        /// <summary>
        /// Creates an HttpRequestMessage for flow-through operations, copying relevant headers from the source request.
        /// When queryParams is null (the default for generated flowthrough code), the incoming request's
        /// query string is forwarded directly. When queryParams is provided (e.g., from an override or
        /// OData alias paths), the dictionary is used to build the query string.
        /// </summary>
        protected virtual HttpRequestMessage CreateFlowThroughRequest(HttpMethod method, string path, HttpRequest sourceRequest, IDictionary<string, object> queryParams = null)
        {
            // Strip module prefix before forwarding
            var forwardPath = StripModulePrefix(path);

            if (queryParams != null)
            {
                // Explicit query params provided (e.g., from an override or OData alias path)
                forwardPath = SubstitutePathAliases(forwardPath, queryParams);
                if (queryParams.Count > 0)
                {
                    forwardPath += BuildQueryString(queryParams);
                }
            }
            else
            {
                // Default flowthrough: forward the incoming query string as-is
                forwardPath += sourceRequest.QueryString.Value ?? string.Empty;
            }

            var request = new HttpRequestMessage(method, forwardPath);

            // Copy relevant headers from source request
            foreach (var header in sourceRequest.Headers)
            {
                // Skip headers that shouldn't be forwarded to the upstream service.
                // Host/Content-Length/Transfer-Encoding are hop-by-hop headers.
                // Origin/Referer are browser-context headers that can cause upstream
                // services to treat API requests as storefront/CORS requests.
                if (header.Key.Equals("Host", StringComparison.OrdinalIgnoreCase) ||
                    header.Key.Equals("Content-Length", StringComparison.OrdinalIgnoreCase) ||
                    header.Key.Equals("Transfer-Encoding", StringComparison.OrdinalIgnoreCase) ||
                    header.Key.Equals("Origin", StringComparison.OrdinalIgnoreCase) ||
                    header.Key.Equals("Referer", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                request.Headers.TryAddWithoutValidation(header.Key, header.Value.ToArray());
            }

            return request;
        }

        /// <summary>
        /// Determines if the incoming request has a body to forward.
        /// </summary>
        private bool HasRequestBody()
        {
            if (Request.ContentLength.HasValue)
                return Request.ContentLength.Value > 0;
            if (Request.Headers.TransferEncoding.Count > 0)
                return true;
            if (!string.IsNullOrEmpty(Request.ContentType))
                return true;
            return false;
        }

        // ============ Core Flow-Through Method ============

        /// <summary>
        /// Core flow-through method - handles authorization, request building, and HTTP execution.
        /// All wrapper methods delegate to this.
        /// </summary>
        /// <param name="method">HTTP method (GET, POST, PUT, PATCH, DELETE)</param>
        /// <param name="path">Request path (module prefix will be stripped)</param>
        /// <param name="queryParams">Optional query parameters</param>
        /// <param name="endpointName">Endpoint name for authorization (auto-populated via CallerMemberName)</param>
        /// <returns>HttpResponseMessage from upstream service</returns>
        /// <exception cref="AuthorizationException">Thrown when authorization fails</exception>
        /// <exception cref="FlowThroughException">Thrown when upstream connection fails</exception>
        protected virtual async Task<HttpResponseMessage> FlowThroughCoreAsync(
            HttpMethod method,
            string path,
            IDictionary<string, object> queryParams = null,
            [System.Runtime.CompilerServices.CallerMemberName] string endpointName = "")
        {
            // Authorization - throws AuthorizationException (caught by exception filter)
            await {projectName}Authorization.GetCallerInfoAsync(this.Request, endpointName);

            var client = HttpClientFactory.CreateClient("{projectName}FlowThrough");
            var request = CreateFlowThroughRequest(method, path, this.Request, queryParams);

            // Conditionally attach body using direct stream forwarding (most efficient)
            if (HasRequestBody())
            {
                request.Content = new StreamContent(this.Request.Body);
                if (!string.IsNullOrEmpty(this.Request.ContentType))
                {
                    request.Content.Headers.ContentType =
                        System.Net.Http.Headers.MediaTypeHeaderValue.Parse(this.Request.ContentType);
                }
            }

            try
            {
                return await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);
            }
            catch (HttpRequestException ex)
            {
                throw new FlowThroughException(502, "BadGateway",
                    $"Failed to connect to upstream service: {ex.Message}", ex);
            }
        }

        // ============ Response Wrapper Methods ============

        /// <summary>
        /// Returns typed response with JSON deserialization.
        /// Use for endpoints that return a single object (e.g., GET by ID, POST, PUT, PATCH).
        /// </summary>
        protected virtual async Task<ActionResult<T>> FlowThroughAsync<T>(
            HttpMethod method,
            string path,
            IDictionary<string, object> queryParams = null,
            [System.Runtime.CompilerServices.CallerMemberName] string endpointName = "")
        {
            using var response = await FlowThroughCoreAsync(method, path, queryParams, endpointName);
            var content = await response.Content.ReadAsStringAsync();

            if (!response.IsSuccessStatusCode)
                return new ContentResult
                {
                    StatusCode = (int)response.StatusCode,
                    Content = content,
                    ContentType = response.Content.Headers.ContentType?.MediaType ?? "application/json"
                };

            var result = Newtonsoft.Json.JsonConvert.DeserializeObject<T>(content);
            return StatusCode((int)response.StatusCode, result);
        }

        /// <summary>
        /// Returns collection response with JSON deserialization.
        /// Use for endpoints that return a list/array of objects.
        /// </summary>
        protected virtual async Task<ActionResult<ICollection<T>>> FlowThroughCollectionAsync<T>(
            HttpMethod method,
            string path,
            IDictionary<string, object> queryParams = null,
            [System.Runtime.CompilerServices.CallerMemberName] string endpointName = "")
        {
            using var response = await FlowThroughCoreAsync(method, path, queryParams, endpointName);
            var content = await response.Content.ReadAsStringAsync();

            if (!response.IsSuccessStatusCode)
                return new ContentResult
                {
                    StatusCode = (int)response.StatusCode,
                    Content = content,
                    ContentType = response.Content.Headers.ContentType?.MediaType ?? "application/json"
                };

            var result = Newtonsoft.Json.JsonConvert.DeserializeObject<ICollection<T>>(content);
            return StatusCode((int)response.StatusCode, result);
        }

        /// <summary>
        /// Returns no content response.
        /// Use for DELETE operations or POST/PUT/PATCH that don't return a body.
        /// </summary>
        protected virtual async Task<IActionResult> FlowThroughNoContentAsync(
            HttpMethod method,
            string path,
            IDictionary<string, object> queryParams = null,
            [System.Runtime.CompilerServices.CallerMemberName] string endpointName = "")
        {
            using var response = await FlowThroughCoreAsync(method, path, queryParams, endpointName);

            if (!response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                return new ContentResult
                {
                    StatusCode = (int)response.StatusCode,
                    Content = content,
                    ContentType = response.Content.Headers.ContentType?.MediaType ?? "application/json"
                };
            }

            return StatusCode((int)response.StatusCode);
        }

        /// <summary>
        /// Streams response directly back to client without buffering.
        /// Use for binary responses (PDF, images) or large payloads.
        /// Most efficient for large responses.
        /// </summary>
        protected virtual async Task<IActionResult> FlowThroughStreamAsync(
            HttpMethod method,
            string path,
            IDictionary<string, object> queryParams = null,
            [System.Runtime.CompilerServices.CallerMemberName] string endpointName = "")
        {
            var response = await FlowThroughCoreAsync(method, path, queryParams, endpointName);

            Response.StatusCode = (int)response.StatusCode;

            // Copy content headers (Content-Type, Content-Length, Content-Disposition, etc.)
            foreach (var header in response.Content.Headers)
            {
                Response.Headers[header.Key] = header.Value.ToArray();
            }

            await response.Content.CopyToAsync(Response.Body);
            return new EmptyResult();
        }

        /// <summary>
        /// Returns raw content preserving content-type.
        /// Use for passthrough without deserialization when you need IActionResult.
        /// </summary>
        protected virtual async Task<IActionResult> FlowThroughContentAsync(
            HttpMethod method,
            string path,
            IDictionary<string, object> queryParams = null,
            [System.Runtime.CompilerServices.CallerMemberName] string endpointName = "")
        {
            using var response = await FlowThroughCoreAsync(method, path, queryParams, endpointName);
            var content = await response.Content.ReadAsStringAsync();

            if (!response.IsSuccessStatusCode)
                return new ContentResult
                {
                    StatusCode = (int)response.StatusCode,
                    Content = content,
                    ContentType = response.Content.Headers.ContentType?.MediaType ?? "application/json"
                };

            return Content(content, response.Content.Headers.ContentType?.MediaType ?? "application/json");
        }
    }
}
