// Generated by LazyMagic from ConfigureSvcs.t.cs - modify ConfigureSvcs.t.cs and then regenerate to update.
// Create a separate ConfigureSvcs.cs file for project specific service configuration.
public partial class Startup
{
    partial void ConfigureSvcs(IServiceCollection services);
}
