// Generated by LazyMagic from GlobalUsing.t.cs - modify GlobalUsing.t.cs and then regenerate to update.
// Create a separate GlobalUsings.cs file for global usings specific to your project.

global using Authentication;
global using Authentication.Extensions;
global using Authentication.Models;
global using HostingMiddleware;
global using Integrations;
global using Integrations.Extensions;
global using LazyMagic.Service.Shared;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Http;
global using Microsoft.Extensions.Logging;
global using Microsoft.IdentityModel.Tokens;
global using NetEscapades.Configuration.Yaml;
global using Newtonsoft.Json.Serialization;
global using Newtonsoft.Json;
global using Polly.Extensions.Http;
global using Polly;
global using RequestRewriter.Service.Extensions;
global using RequestRewriter.Base;
global using Secrets.Base;
global using Secrets.ASM.Extensions;
