// Generated by LazyMagic from Program.t.cs - modify Program.t.cs and regenerate to update.

using Serilog;

// Configure Serilog to write to console (stdout) for CloudWatch via ECS awslogs driver
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .MinimumLevel.Override("Microsoft", Serilog.Events.LogEventLevel.Warning)
    .MinimumLevel.Override("System", Serilog.Events.LogEventLevel.Warning)
    .WriteTo.Console()
    .CreateLogger();

var builder = WebApplication.CreateBuilder(args);

// Use Serilog for logging
builder.Host.UseSerilog();

// Load tenant/system configuration into IConfiguration.
// Discovery order (first match wins):
//   1. tenantconfig.{sk}.{tk}.{env}.yaml  — tenant-specific (preferred)
//   2. config.*.{env}.yaml / config.*.yaml — old convention
//   3. tenantconfig.yaml / tenantconfig.{env}.yaml — legacy
//   4. systemconfig.yaml / systemconfig.{env}.yaml — legacy fallback
// Environment is detected from env.yaml or folder name convention (_Dev*, _Test*, _Prod*)
var configPath = UtilModule.SystemConfigResolver.ResolveFromApphostData();

// If no config found locally, try to download from SSM Parameter Store.
// This happens on first container start before the config is cached on EFS.
if (configPath is null)
{
    var sk = Environment.GetEnvironmentVariable("LZ_SYSTEM_KEY");
    var tk = Environment.GetEnvironmentVariable("LZ_TENANT_KEY");
    var lzEnv = Environment.GetEnvironmentVariable("LZ_ENVIRONMENT");
    var awsRegion = Environment.GetEnvironmentVariable("AWS_REGION") ?? "us-west-2";

    if (sk != null && tk != null && lzEnv != null)
    {
        try
        {
            Console.WriteLine($"No local config found. Downloading from SSM: /{sk}/{tk}/{lzEnv}/tenantconfig");
            using var ssmClient = new Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementClient(
                Amazon.RegionEndpoint.GetBySystemName(awsRegion));
            var param = await ssmClient.GetParameterAsync(
                new Amazon.SimpleSystemsManagement.Model.GetParameterRequest
                {
                    Name = $"/{sk}/{tk}/{lzEnv}/tenantconfig",
                });

            // Write to EFS-mounted config directory so it persists across restarts
            var dataPath = UtilModule.ApphostDataPathResolver.GetPath();
            var configDir = Path.Combine(dataPath, "config");
            Directory.CreateDirectory(configDir);
            var localPath = Path.Combine(configDir, $"tenantconfig.{sk}.{tk}.{lzEnv}.yaml");
            await File.WriteAllTextAsync(localPath, param.Parameter.Value);

            configPath = localPath;
            Console.WriteLine($"Downloaded tenant config from SSM to {localPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Warning: Failed to download config from SSM: {ex.Message}");
        }
    }
}

if (configPath is not null)
{
    builder.Configuration.AddYamlFile(configPath, optional: true, reloadOnChange: false);
    Console.WriteLine($"Loaded configuration from {configPath}");
}
else
{
    Console.WriteLine("Warning: No tenant or system configuration found in apphost data");
}

// Add services to the container
builder.Services.AddControllers()
    .AddNewtonsoftJson();

builder.Services.AddHttpContextAccessor();
builder.Services.AddHttpClient();

// Configure multi-scheme authentication from configuration
builder.Services.AddMultiSchemeAuthentication(builder.Configuration);

// Add CORS
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.SetIsOriginAllowed(origin =>
                  origin.StartsWith("https://") || origin.StartsWith("http://"))
              .WithHeaders(
                  "Authorization",
                  "lz-auth-id",
                  "lz-authname")
              .AllowAnyHeader()
              .WithMethods(
                  "GET",
                  "HEAD",
                  "PUT",
                  "OPTIONS",
                  "PATCH",
                  "POST",
                  "DELETE")
              .WithExposedHeaders(
                  "Date",
                  "x-api-id",
                  "lz-auth-id",
                  "lz-authname")
              .SetPreflightMaxAge(TimeSpan.FromSeconds(600))
              .DisallowCredentials();
    });
});

// Add health checks
builder.Services.AddHealthChecks();

// Add request logging
builder.Services.AddRequestLogging(builder.Configuration);

// Add request rewriter
builder.Services.AddRequestRewriter(builder.Configuration);

// Configure services (will be generated)
var startup = new Startup(builder.Configuration);
startup.ConfigureServices(builder.Services);

var app = builder.Build();

// Configure the HTTP request pipeline
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

// Request logging (early in pipeline to capture all requests)
app.UseRequestLogging();

// Apply request path rewrites (BEFORE routing so routes match rewritten paths)
app.UseRequestRewriter();

app.UseRouting();

app.UseCors();

// Multi-scheme authentication middleware
app.UseMultiSchemeAuthenticationMiddleware();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapHealthChecks("/health");

// Hook for host-specific endpoint mapping (e.g., SignalR hubs)
startup.ConfigureEndpoints(app);

app.Run();
