using Lz.Core.Orchestration;

namespace Lz.Core.Definitions;

public enum IngressType
{
    Public,
    Internal,
    None
}

/// <summary>
/// Determines when a service is deployed in the phase sequence.
/// Services layer deploys first; Host layer deploys after services are operational.
/// </summary>
public enum ServiceLayer
{
    /// <summary>
    /// Foundation-level services shared across all tenants.
    /// Deployed during deploysystem, not per-tenant.
    /// Examples: LiveKit SFU, shared message broker.
    /// </summary>
    Foundation,

    /// <summary>
    /// Core services deployed first. May require seeding, manual admin
    /// interaction, or secret generation before host-layer services can start.
    /// </summary>
    Service,

    /// <summary>
    /// Services that depend on the service layer being operational
    /// (e.g., need secrets generated by SmartStore).
    /// </summary>
    Host
}

public class ServiceDefinition
{
    public string Name { get; set; } = string.Empty;
    public ServiceLayer Layer { get; set; } = ServiceLayer.Service;
    public IngressType IngressType { get; set; } = IngressType.Public;
    public string HostPattern { get; set; } = string.Empty;
    public bool RequiresDatabase { get; set; }
    public bool RequiresEmail { get; set; }
    public List<VolumeMount> Volumes { get; set; } = new();
    public List<SecretRef> Secrets { get; set; } = new();
    public List<ApiRoute> Routes { get; set; } = new();
    public ContainerOptions? Container { get; set; }
    public LambdaOptions? Lambda { get; set; }

    /// <summary>
    /// Docker build configuration. If set, the services post-deploy action
    /// builds and pushes the image to ECR automatically.
    /// </summary>
    public DockerBuildOptions? Docker { get; set; }

    /// <summary>
    /// Transition requirements that must be met before this service's
    /// post-deploy actions (build/push/scale) run. Checked after the
    /// prior layer's services are operational.
    /// </summary>
    public List<TransitionRequirement> TransitionRequirements { get; set; } = new();
}

/// <summary>
/// Docker build and push configuration for a service.
/// Paths are relative to the monorepo root (where systemconfig lives).
/// </summary>
public class DockerBuildOptions
{
    /// <summary>Build context directory, relative to monorepo root (e.g., "Smartstore").</summary>
    public string Context { get; set; } = string.Empty;

    /// <summary>Dockerfile path, relative to context (e.g., "monro/Dockerfile").</summary>
    public string Dockerfile { get; set; } = "Dockerfile";

    /// <summary>Optional build arguments (e.g., ContainerName=AppHost).</summary>
    public Dictionary<string, string> BuildArgs { get; set; } = new();
}

public class ContainerOptions
{
    public int Cpu { get; set; }
    public int Memory { get; set; }
    public int Port { get; set; } = 80;
    public string Protocol { get; set; } = "HTTP";
    public string HealthCheckPath { get; set; } = "/health";

    /// <summary>
    /// Additional port mappings for services that need multiple protocols (e.g., TCP + UDP).
    /// If empty, only the primary Port/Protocol is used.
    /// </summary>
    public List<PortMapping> AdditionalPorts { get; set; } = new();
}

/// <summary>
/// A port or port range with protocol specification.
/// Used for services that need UDP (e.g., WebRTC media servers).
/// </summary>
public class PortMapping
{
    public int Port { get; set; }
    public int? ToPort { get; set; }  // For port ranges (e.g., 7882-7900)
    public string Protocol { get; set; } = "tcp";  // "tcp" or "udp"
}

public class LambdaOptions
{
    public int MemorySize { get; set; } = 512;
    public int Timeout { get; set; } = 30;
    public string? Handler { get; set; }
    public string Runtime { get; set; } = "dotnet8";
}

public class VolumeMount
{
    public string Name { get; set; }
    public string ContainerPath { get; set; }
    public string EfsPath { get; set; }

    public VolumeMount(string name, string containerPath, string efsPath)
    {
        Name = name;
        ContainerPath = containerPath;
        EfsPath = efsPath;
    }
}

public class SecretRef
{
    public string Name { get; set; } = string.Empty;
    public string SecretId { get; set; } = string.Empty;
}

public class ApiRoute
{
    public string Path { get; set; } = string.Empty;
    public ApiRoute() { }
    public ApiRoute(string path) { Path = path; }
}
