namespace Lz.Core.Config;

/// <summary>
/// Durability protections for the durable resources lz manages. Maps to the
/// "Durability:" section in systemconfig.{systemkey}.{env}.yaml.
///
/// <para>SCOPE, which has grown and is easy to under-read. Originally the
/// per-subtenant vault/PII table only; it now covers, each through its own named
/// decision in <c>TableDurabilityPolicy</c> / <c>CognitoDurabilityPolicy</c>:
/// the subtenant vault table, the Cognito custom-auth VENDOR CREDENTIAL table,
/// the SYSTEM table ({sk}), the TENANT table ({sk}_{tk}), the BFF SESSION tables
/// ({sk}_{tk}_bff / _cbff / _abff), and the COGNITO USER POOLS.</para>
///
/// <para>The decisions are NOT uniform, and the divergence is deliberate: BFF
/// session tables take deletion protection but NOT point-in-time recovery,
/// because their rows are regenerated by re-login and TTL is deleting from them
/// continuously — a restore would resurrect sessions the system expired on
/// purpose. Cognito pools take deletion protection only, because Cognito has no
/// PITR concept at all. Read the per-class functions rather than assuming both
/// flags apply everywhere.</para>
///
/// <para>ABSENT = OFF, DELIBERATELY. When the section is omitted (or a flag is
/// false) NOTHING is applied: the CreateTable request leaves
/// <c>DeletionProtectionEnabled</c> unset and no
/// <c>UpdateContinuousBackups</c> call is made, so the emitted table is
/// byte-for-byte identical to a pre-durability deploy. This is what keeps
/// systems that don't opt in (e.g. MagicPets) unchanged — the flags gate
/// EXTRA calls, they never alter the baseline request. The same rule holds for
/// the Pulumi-managed resources: the vendor-credential table's args and the user
/// pool's <c>DeletionProtection</c> are ASSIGNED ONLY when opted in, because
/// assigning an explicit <c>false</c>/<c>INACTIVE</c> is not the same plan as not
/// assigning the property, even where it matches the service default.</para>
///
/// <para>ONE-WAY, PRACTICALLY. Nothing here ever DISABLES a protection: the
/// imperative path only ever enables (guarded on the current state), so flipping a
/// flag back to false in YAML appears to work and does nothing to an already-
/// protected table. Turning protection off is a manual, per-service operation —
/// see the teardown note in Docs/reference/operations/runbooks.md, and do not
/// reach for a bare <c>update-user-pool</c>, which resets every attribute you
/// omit.</para>
///
/// <para>Point-in-time recovery is the recovery net that makes the deliberate
/// <c>--force-delete-protected</c> teardown path acceptable — a forced delete
/// of a protected table is still restorable from a continuous backup.
/// Encryption at rest with a customer-managed key is a SEPARATE concern and is
/// intentionally NOT modelled here.</para>
/// </summary>
public class DurabilityConfig
{
    /// <summary>
    /// Enable DynamoDB deletion protection on the subtenant table. Default
    /// <c>false</c>. When true, the table cannot be deleted until protection is
    /// explicitly disabled — so <c>lz destroysubtenant</c> REFUSES a protected
    /// table unless the operator passes <c>--force-delete-protected</c> (which
    /// disables protection, then deletes).
    /// </summary>
    public bool DeletionProtection { get; set; } = false;

    /// <summary>
    /// Enable DynamoDB point-in-time recovery (continuous backups) on the
    /// subtenant table. Default <c>false</c>. Applied via a post-create
    /// <c>UpdateContinuousBackups</c> call (PITR is not a CreateTable field),
    /// and re-asserted idempotently on subsequent ensures.
    /// </summary>
    public bool PointInTimeRecovery { get; set; } = false;

    /// <summary>
    /// Enable S3 versioning on the CONTENT buckets lz creates — the system and tenant
    /// assets buckets, the CDN assets bucket, and every web-app and static-site bucket.
    /// Default <c>false</c>.
    ///
    /// <para>Every publish path mirrors a local tree into these buckets with
    /// <c>aws s3 sync --delete</c>, so on an unversioned bucket a bad publish is PERMANENT:
    /// no delete marker, no noncurrent version, nothing to restore, and enabling versioning
    /// afterwards resurrects nothing. This is what makes a bundle rollback possible at all.
    /// </para>
    ///
    /// <para>Requires <see cref="HygieneConfig.S3NoncurrentVersionExpirationDays"/> — the
    /// validator refuses versioning without it, because the console bundles are republished
    /// in full on every deploy and an unbounded version history grows by a whole bundle each
    /// time. That number IS the rollback window.</para>
    ///
    /// <para>One-way: S3 versioning can be suspended but never disabled. The per-subtenant
    /// assets bucket and the Pulumi state bucket are already versioned regardless of this
    /// flag and are not affected by it.</para>
    /// </summary>
    public bool BucketVersioning { get; set; } = false;
}
