namespace Lz.Core.Config;

/// <summary>
/// Pulumi state backend configuration.
/// Auto-generated by ConfigLoader from SystemSuffix/SharedSuffix — not read from YAML.
/// </summary>
public class StateConfig
{
    /// <summary>
    /// Pulumi backend URL.
    /// e.g., "s3://med-dev-pulumi-state-4498-a704?region=us-west-2"
    /// </summary>
    public string Backend { get; set; } = string.Empty;

    /// <summary>
    /// Pulumi secrets provider URL.
    /// e.g., "awskms://alias/med-dev-pulumi-key-4498-a704"
    /// </summary>
    public string SecretsProvider { get; set; } = string.Empty;
}
