namespace Lz.Core.Config;

public class SubtenantEntry
{
    /// <summary>
    /// Leftmost DNS label of the subtenant's first-level subdomain under the
    /// tenant's <c>RootDomain</c>. The full host is constructed as
    /// <c>{SubDomain}.{RootDomain}</c> at consumption sites — never spell
    /// the FQDN out here.
    /// <para>
    /// Optional. Defaults to the subtenant key when empty/omitted. In nearly
    /// every case the subtenant key already IS the desired label (cerulean,
    /// walv, free, …) so this field can be dropped entirely from the YAML.
    /// Only set it when the subtenant key and the customer-facing label
    /// must differ.
    /// </para>
    /// <para>
    /// Validation (<see cref="ConfigValidator"/>): when non-empty must be a
    /// single DNS label (1–63 chars, alphanumeric + hyphen, starting and
    /// ending alphanumeric, no dots). The previous schema accepted full
    /// FQDNs (<c>cerulean.eventitdev.click</c>) and validated that they
    /// were first-level under <c>RootDomain</c>; that was redundant — the
    /// tenant config already supplies <c>RootDomain</c>, so duplicating it
    /// per subtenant just invited drift between the two.
    /// </para>
    /// </summary>
    public string SubDomain { get; set; } = string.Empty;
    public BehaviorsConfig? Behaviors { get; set; }

    /// <summary>
    /// Customer-facing display name for the subtenant (e.g.
    /// <c>"Cerulean Beach Resort"</c>). Surfaced on tenant-level
    /// listings (the central "venues" page generated by deploy plugins
    /// from this metadata). Optional; defaults to the subtenant key
    /// title-cased at consumption time when empty/omitted.
    /// </summary>
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>
    /// Short marketing description for the subtenant. Optional.
    /// Surfaced on tenant-level listings alongside
    /// <see cref="DisplayName"/>. Empty/omitted → no description shown.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// URL of a logo image to render on tenant-level listings.
    /// Optional. Accepts a host-rooted path (e.g.
    /// <c>"/subtenancy/base/SetsApp/imgs/HEADER.png"</c>) — deploy
    /// plugins typically prepend the subtenant origin at generation
    /// time so the listing page can render the image cross-origin
    /// without resolving the path itself.
    /// </summary>
    public string LogoUrl { get; set; } = string.Empty;

    /// <summary>
    /// Whether to include this subtenant on the central tenant-level
    /// <c>/venues/</c> listing page. Default <c>true</c> — set to
    /// <c>false</c> to hide a subtenant (e.g. internal/demo accounts,
    /// soft-launched venues, customers under NDA). The subtenant still
    /// resolves correctly when visited directly; only its presence in
    /// the venues directory is suppressed.
    /// </summary>
    public bool IncludeOnVenuesPage { get; set; } = true;

    /// <summary>
    /// Controls the CTA layout for this subtenant on the central
    /// <c>/venues/</c> listing page. The renderer combines this setting
    /// with the visitor's auth state and the resolved
    /// <c>WebApps[/].AuthConfig</c> (cascade-resolved at deploy time)
    /// to choose between three button labels:
    /// <list type="bullet">
    ///   <item><description><b>"Visit"</b> — always
    ///     <c>/explore/home/</c> (the subtenant's branded landing
    ///     page).</description></item>
    ///   <item><description><b>"Use App"</b> — <c>/</c> (the WASM
    ///     app), shown when the subtenant is public OR the visitor is
    ///     already authenticated cross-subtenant.</description></item>
    ///   <item><description><b>"Login"</b> —
    ///     <c>/authentication/login?returnUrl=/</c>, shown for gated
    ///     subtenants when the visitor isn't authed yet.</description></item>
    /// </list>
    /// <c>VenuesLinkMode</c> picks WHICH of these to render. Case-
    /// insensitive; one of:
    /// <list type="bullet">
    ///   <item>
    ///     <term><c>"both"</c> (default)</term>
    ///     <description>"Visit" primary + contextual secondary
    ///     ("Use App" or "Login"). Best general-purpose choice — the
    ///     visitor always has a path through the marketing pitch AND
    ///     a direct shortcut when applicable.</description>
    ///   </item>
    ///   <item>
    ///     <term><c>"app"</c></term>
    ///     <description>Only the contextual button — "Use App" or
    ///     "Login". Use when you don't want to surface
    ///     <c>/explore/home/</c> on the venues page at all.</description>
    ///   </item>
    ///   <item>
    ///     <term><c>"landing"</c></term>
    ///     <description>Only "Visit". Use when every visitor should
    ///     see the subtenant's branded landing page before entering
    ///     the app, regardless of auth state.</description>
    ///   </item>
    /// </list>
    /// Validated by <see cref="ConfigValidator"/>; an unrecognized
    /// value rejects the config at load time.
    /// </summary>
    public string VenuesLinkMode { get; set; } = "both";
}
