<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lz.Cli</RootNamespace>

    <!-- Global tool packaging -->
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>lz</ToolCommandName>
    <PackageId>Lz.Cli</PackageId>
    <Version>0.9.80</Version>
    <Description>Lz infrastructure deployment tool</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lz.Core\Lz.Core.csproj" />
    <ProjectReference Include="..\Lz.Aws\Lz.Aws.csproj" />
    <ProjectReference Include="..\Lz.Azure\Lz.Azure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

</Project>
