<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lz.Azure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lz.Core\Lz.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pulumi.AzureNative" Version="2.*" />
  </ItemGroup>

</Project>
